version: "3.0"

services:
  fpm:
    build:
      context: .docker
      dockerfile: php-fpm/Dockerfile
      args:
        user: sammy
        uid: 1000
    container_name: ${APP_PREFIX}-fpm
    working_dir: /var/www/
    volumes:
      - ./magento:/var/www/magento

  nginx:
    build:
      context: .docker
      dockerfile: nginx/Dockerfile
    container_name: ${APP_PREFIX}-nginx
    ports:
      - ${NGINX_EXT_HTTP}:80
      - ${NGINX_EXT_HTTPS}:443
    depends_on:
      - fpm
    volumes:
      - ./.docker/nginx/conf/:/etc/nginx/conf.d/
      - ./magento:/var/www/magento

  mysql:
    image: mysql:8.0
    container_name: ${APP_PREFIX}-mysql
    env_file: .docker/mysql/.env
    ports:
      - "${MYSQL_EXT_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d

  search:
    image: opensearchproject/opensearch:2.5.0
    container_name: ${APP_PREFIX}-search
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    volumes:
      - searchdata:/usr/share/opensearch/data
    
  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_PREFIX}-phpmyadmin
    ports:
      - "${PHPMYADMIN_EXT_PORT}:80"
    environment:
      - PMA_HOST=mysql
      - PMYSQL_ROOT_PASSWORD=

volumes:
  dbdata: {}
  searchdata: {}