version: "1.0"

services:  
  app:
    build: .docker/apache
    container_name: ${APP_PREFIX}-app
    ports:
      - "${APACHE_EXT_HTTP}:80"
      - "${APACHE_EXT_HTTPS}:443"
    links:
      - mysql
      - search
    volumes:
      - ./magento:/var/www/html/

  mysql:
    image: mysql:8.0
    container_name: ${APP_PREFIX}-mysql
    env_file: .docker/mysql/.env
    ports:
      - "${MYSQL_EXT_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d

  search:
    image: opensearchproject/opensearch:2.5.0
    container_name: ${APP_PREFIX}-search
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    volumes:
      - searchdata:/usr/share/opensearch/data

volumes:
  dbdata: {}
  searchdata: {}