version: "3.0"

services:  
  app:
    build: 
      context: .docker
      dockerfile: apache/Dockerfile
    container_name: ${APP_PREFIX}-app
    ports:
      - "${APACHE_EXT_HTTP}:80"
      - "${APACHE_EXT_HTTPS}:443"
    volumes:
      - ./magento:/var/www/html/
  
  mysql:
    image: mysql:8.0
    container_name: ${APP_PREFIX}-mysql
    env_file: .docker/mysql/.env
    ports:
      - "${MYSQL_EXT_PORT}:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_PREFIX}-phpmyadmin
    ports:
      - "${PHPMYADMIN_EXT_PORT}:80"
    environment:
      - PMA_HOST=mysql
      - PMYSQL_ROOT_PASSWORD=

  search:
    image: opensearchproject/opensearch:2.5.0
    container_name: ${APP_PREFIX}-search
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
    volumes:
      - searchdata:/usr/share/opensearch/data

volumes:
  dbdata: {}
  searchdata: {}