#!/bin/bash
BASE_DIR=/var/www/html

SETUP=0

if [ ! -f "$BASE_DIR/composer.lock" ]; 
then
    SETUP=0
else
    SETUP=1
fi

if [ ! -d "$BASE_DIR/vendor/magento" ]; 
then
    cd /var/www/html
    echo "Running composer install"
    composer install
    echo "Composer install complete !"

    if [ SETUP==0 ]; 
    then
        echo "Magento Setup init"
        php bin/magento setup:install \
            --base-url="http://localhost:8080/pub/" \
            --db-host="mysql" \
            --db-name="magento" \
            --db-user="magento" \
            --db-password="magento" \
            --admin-firstname="Admin" \
            --admin-lastname="User" \
            --admin-email="admin@test.com" \
            --admin-user="admin" \
            --admin-password="Test@123" \
            --use-rewrites="1" \
            --backend-frontname="admin" \
            --session-save="files" \
            --key="your-crypt-key" \
            --search-engine="opensearch" \
            --opensearch-host="search" \
            --opensearch-port="9200" 

        echo "Magento Setup complete"
    fi
    
    echo "Deploying magento"
    
    if [ SETUP==1 ];
    then
        mv /usr/local/bin/env.php app/etc/env.php
    fi

    php bin/magento setup:upgrade
    echo "Deployment complete !"
fi

echo "Starting Apache"
apache2-foreground